services:
  redis-cache:
    image: redis:alpine

  redis-queue:
    image: redis:alpine

  redis-socketio:
    image: redis:alpine

  mariadb:
    container_name: mariadb
    image: mariadb:10.6
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
    - maria_db_data:/var/lib/mysql
    ports:
    - "3306:3306" 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


  frappe-docker: 
    image: kraegavila/frappe-custom:v.0.6
    container_name: frappe-docker
    tty: true
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio
    
    volumes:
    - ./bench-version-15-base-database.sql.gz:/home/frappe/bench-version-15/bench-version-15-base-database.sql.gz:ro
    ports:
      - 8000:8000
      - 9000:9000


volumes:
  maria_db_data:


