services:
  redis-cache:
    image: redis:alpine

  redis-queue:
    image: redis:alpine

  redis-socketio:
    image: redis:alpine

  mariadb:
    container_name: mariadb-asn_docker
    image: mariadb:10.6
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    # ports:
    #   - "3305:3306"
    volumes:
    - maria_db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  smr_asn_docker:
    build:
      context: .
      dockerfile: Dockerfile
    image: smr/asn_docker:v.0.1
    container_name: asn_docker
    tty: true
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio
    volumes:
      - ./frappe-15-asn_docker.sql.gz:/home/frappe/bench-version-15/frappe-15-asn_docker.sql.gz:ro
    ports:
      - "8000:8000" 
      - "9000:9000" 
    



volumes:
  maria_db_data:
